trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js ss'

          - script: |
              npm install
              npm run build
            displayName: 'npm install and build'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish artifact'
            inputs:
              targetPath: '$(Pipeline.Workspace)/s'
              artifactType: 'pipeline'
              artifactName: 'app'
  - stage: Dev
    jobs:
      - template: ci-cd/deploy.yml
        parameters:
          host: 'ec2-user@ec2-52-56-187-118.eu-west-2.compute.amazonaws.com'
          env: dev
  - stage: Prod
    jobs:
      - template: ci-cd/deploy.yml
        parameters:
          host: 'ec2-user@ec2-13-40-19-71.eu-west-2.compute.amazonaws.com'
          env: prod
