parameters:
  - name: host
    type: string
  - name: env
    type: string

jobs:
  - deployment: Dep_x
    displayName: Deploy
    environment:
      name: ${{ parameters.env }}
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - script: |
                echo 'pwd'
                pwd
                echo 'ls -ltr'
                ls -ltr
                echo 'ls  $(Pipeline.Workspace)'
                ls -l  $(Pipeline.Workspace)
              displayName: 'pwd and ls -ltr'
            - script: |
                curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
                . ~/.nvm/nvm.sh

                nvm install 17.1.0
                node -v

                rm -rf /tmp/app
                sudo rm -rf /srv/app

                mkdir /tmp/app
                sudo mkdir /srv/app
                sudo chown ec2-user /srv/app

                cp -r $(Pipeline.Workspace)/app/* /tmp/app

                sudo cp -r /tmp/app/* /srv/app
                sudo chown -R ec2-user /srv/app
                chmod u+x /srv/app/server.js

                echo 'sudo systemctl status myapp'
                sudo systemctl status myapp

                echo 'sudo systemctl stop myapp || true'
                sudo systemctl stop myapp || true

                echo 'systemctl status myapp'
                sudo systemctl status myapp

                echo 'sudo cp /srv/app/myapp.service /etc/systemd/system'
                sudo cp /srv/app/myapp.service /etc/systemd/system

                echo 'sudo systemctl daemon-reload'
                sudo systemctl daemon-reload

                echo 'sudo systemctl enable myapp'
                sudo systemctl enable myapp

                echo 'sudo systemctl start myapp'
                sudo systemctl start myapp

                echo 'sudo systemctl status myapp'
                journalctl -n 10 -ru myapp
              displayName: 'start app'
