parameters:
  - name: host
    type: string
  - name: env
    type: string

jobs:
  - deployment: Deploy
    environment:
     name: ${{ parameters.env }}
    resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - script: |
                echo 'pwd'
                pwd

                echo 'ls -ltr'
                ls -ltr
              displayName: 'remote commands'
